// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0UeQYFKaO_mnPWryAnNRGiAuAHh-FtCg',
    appId: '1:221546725576:web:4c0dc09808c06c700c25fd',
    messagingSenderId: '221546725576',
    projectId: 'shibu-fire',
    authDomain: 'shibu-fire.firebaseapp.com',
    storageBucket: 'shibu-fire.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn-4WRncmisnGpR8SqytoPHXVltQl1UL4',
    appId: '1:221546725576:android:63f6a4effb1d4ee70c25fd',
    messagingSenderId: '221546725576',
    projectId: 'shibu-fire',
    storageBucket: 'shibu-fire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxOFXxsjw8yUflX9vmpfrjSpPQZuAm47w',
    appId: '1:221546725576:ios:69efaa8bc0bc43aa0c25fd',
    messagingSenderId: '221546725576',
    projectId: 'shibu-fire',
    storageBucket: 'shibu-fire.appspot.com',
    iosBundleId: 'com.example.shibuFire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxOFXxsjw8yUflX9vmpfrjSpPQZuAm47w',
    appId: '1:221546725576:ios:69efaa8bc0bc43aa0c25fd',
    messagingSenderId: '221546725576',
    projectId: 'shibu-fire',
    storageBucket: 'shibu-fire.appspot.com',
    iosBundleId: 'com.example.shibuFire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0UeQYFKaO_mnPWryAnNRGiAuAHh-FtCg',
    appId: '1:221546725576:web:6da9fdcee72434560c25fd',
    messagingSenderId: '221546725576',
    projectId: 'shibu-fire',
    authDomain: 'shibu-fire.firebaseapp.com',
    storageBucket: 'shibu-fire.appspot.com',
  );
}
